import os

from flask import Flask, render_template, request, redirect, session
from werkzeug.security import check_password_hash, generate_password_hash
from functools import wraps
import sqlite3

app = Flask(__name__)

app.secret_key = os.environ.get("SECTRET_KEY", "dev_secret_key")

def login_required(f):
    @wraps(f)
    def wrapper(*args, **kwargs):
        if session.get("user_id") is None:
            return redirect("/login")
        return f(*args, **kwargs)
    return wrapper

def init_db():
    conn = sqlite3.connect('database.db')
    cursor = conn.cursor()

    cursor.execute('''CREATE TABLE IF NOT EXISTS users
                (id INTEGER PRIMARY KEY AUTOINCREMENT,
                points INTEGER DEFAULT 0,
                username TEXT UNIQUE NOT NULL,
                password TEXT NOT NULL)''') 
    cursor.execute('''CREATE TABLE IF NOT EXISTS tasks
                (id INTEGER PRIMARY KEY AUTOINCREMENT,
                status TEXT NOT NULL,
                timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
                task TEXT NOT NULL,
                user_id INTEGER REFERENCES users(id))''')
    cursor.execute('''CREATE TABLE IF NOT EXISTS quotes
                 (id INTEGER PRIMARY KEY AUTOINCREMENT, 
                 quote TEXT NOT NULL) ''')

    # quotes generated by chatgpt
    quotes = [
                "Small steps every day add up to big results.",
                "Action beats motivation.",
                "Done is better than perfect.",
                "Focus on progress, not perfection.",
                "You don't need more time, you need more focus.",
                "Discipline is choosing what you want most over what you want now.",
                "Start where you are. Use what you have. Do what you can.",
                "Consistency will take you where motivation can't.",
                "The hardest part is starting.",
                "One task at a time.",
                "Your future self is watching.",
                "You are capable of more than you think.",
                "Progress, not pressure.",
                "Do the next right thing.",
                "Clarity comes from action.",
                "Little wins matter.",
                "Momentum is built, not found.",
                "Work with your energy, not against it.",
                "You don't have to feel ready to begin.",
                "Finish what you start.",
                "Habits shape your future.",
                "Focus creates freedom.",
                "Effort compounds.",
                "You're closer than you think.",
                "Show up, even imperfectly.",
                "Structure creates calm.",
                "Start messy. Refine later.",
                "Your goals deserve consistency.",
                "Make today count.",
                "You are building something meaningful."
            ]
    
    for quote in quotes:
        cursor.execute("INSERT INTO quotes (quote) VALUES (?)", (quote, ))

    conn.commit()
    conn.close()

init_db()

def get_db():
    return sqlite3.connect('database.db')

def get_points():
    conn = get_db()
    cursor = conn.cursor()
    cursor.execute("SELECT points FROM users WHERE id = ?", (session["user_id"], ))
    row = cursor.fetchone()[0]
    if row is None:
        return 0
    return row


@app.route("/register", methods=["GET", "POST"])
def register():
    if request.method == "GET":
        return render_template("register.html")
    
    elif request.method == "POST":
        username = request.form.get("username")
        password = request.form.get("password")
        confirmation = request.form.get("confirmation")

        if not username or not password or not confirmation:
            return "Username and password are required", 400
        elif password != confirmation:
            return "Passwords do not match", 400
        
        try:
            hashed_password = generate_password_hash(password)
            conn = get_db()
            cursor = conn.cursor()
            cursor.execute("INSERT INTO users (username, password) VALUES (?, ?)", (username, hashed_password))
            conn.commit()
            conn.close()
            return redirect("/login")
        except sqlite3.IntegrityError:
            return "Username already exists", 409
        
        
@app.route("/login", methods=["GET", "POST"])
def login():
    session.clear()
    if request.method == "GET":
        return render_template("login.html")
    elif request.method == "POST":
        username = request.form.get("username")
        password = request.form.get("password")

        if not username or not password:
            return "Username and password are required", 400

        conn = get_db()
        cursor = conn.cursor()
        cursor.execute("SELECT id, username, password FROM users WHERE username = ?", (username, ))
        user = cursor.fetchone()

        if user is None or not check_password_hash(user[2], password):
            return "Invalid username or password", 401 

        else:
            session["user_id"] = user[0]
            session["username"] = user[1]
            conn.close()
            return redirect("/")
        

@app.route("/logout")
@login_required
def logout():
    session.clear()
    return redirect("/login")


@app.route("/", methods=["GET", "POST"])
@login_required
def index():
    if request.method == "GET":      
        conn = get_db()
        cursor = conn.cursor()

        cursor.execute("SELECT task FROM tasks WHERE status = 'to do' AND user_id = ?", (session["user_id"], ))
        tasks = cursor.fetchall()

        cursor.execute("SELECT task FROM tasks WHERE status = 'doing' AND user_id = ?", (session["user_id"], ))
        doing = cursor.fetchall()

        cursor.execute("SELECT task FROM tasks WHERE status = 'done' AND user_id = ?", (session["user_id"], ))
        done = cursor.fetchall()

        cursor.execute("SELECT quote FROM quotes ORDER BY RANDOM() LIMIT 1")
        quote = cursor.fetchone()[0]

        conn.commit()
        conn.close()
        return render_template("index.html", tasks=tasks, doing=doing, done=done, quote=quote )
    
    elif request.method == "POST":

        # get the task the user entered
        task = request.form.get("task")
        to_do = request.form.get("btn_to_do")
        doing = request.form.get("btn_doing")
        done = request.form.get("btn_done")

        conn = get_db()
        cursor = conn.cursor() 

        if task:
            cursor.execute("INSERT INTO tasks (status, task, user_id) VALUES (?, ?, ?)", ("to do", task, session["user_id"], ))


        elif to_do:
            cursor.execute("INSERT INTO tasks (status, task, user_id) VALUES (?, ?, ?)", ("doing", to_do, session["user_id"], ))
            cursor.execute("DELETE FROM tasks WHERE task = ? AND user_id = ? AND status = ?", (to_do, session["user_id"], "to do",))

        elif doing:
            cursor.execute("INSERT INTO tasks (status, task, user_id) VALUES (?, ?, ?)", ("done", doing, session["user_id"], ))
            cursor.execute("DELETE FROM tasks WHERE task = ? AND user_id = ? AND status = ?", (doing, session["user_id"], "doing",))
            cursor.execute("UPDATE users SET points = points + 100 WHERE id = ?", (session["user_id"], ))

        elif done:
            cursor.execute("DELETE FROM tasks WHERE task = ? AND user_id = ? AND status = ?", (done, session["user_id"], "done",))
        conn.commit()
        
        cursor.execute("SELECT task FROM tasks WHERE status = 'to do' AND user_id = ?", (session["user_id"], ))
        tasks = cursor.fetchall()

        cursor.execute("SELECT task FROM tasks WHERE status = 'doing' AND user_id = ?", (session["user_id"], ))
        doing = cursor.fetchall()

        cursor.execute("SELECT task FROM tasks WHERE status = 'done' AND user_id = ?", (session["user_id"], ))
        done = cursor.fetchall()

        cursor.execute("SELECT quote FROM quotes ORDER BY RANDOM() LIMIT 1")
        quote = cursor.fetchone()[0]

        conn.close()

        return render_template("index.html", tasks=tasks, doing=doing, done=done, quote=quote)

@app.route("/about")
@login_required
def about():
    return render_template("about.html")

@app.route("/mood", methods=["GET", "POST"])
@login_required
def mood():

    points = get_points()
    if not points > 500:
        return "Not enough points yet"
    
    if request.method == "GET":     
        return render_template("mood.html") 
    
    elif request.method == "POST":
        happy = request.form.get("happy")
        focused = request.form.get("focused")
        creative = request.form.get("creative")
        calm = request.form.get("calm")
        tired = request.form.get("tired")
        stressed = request.form.get("stressed")

        # tasks generated by chatgpt
        if happy:
            tasks = [
                        "Call or text a friend you have not spoken to in a while",
                        "Bake cookies or try a new recipe",
                        "Go for a short jog or dance to your favorite music",
                        "Organize your workspace or room",
                        "Compliment someone or do a random act of kindness",
                        "Listen to an upbeat playlist while doing chores",
                        "Finish a small personal goal",
                        "Take photos of something that makes you smile",
                        "Write a gratitude list",
                        "Try a fun hobby for 30 minutes (drawing, DIY, crafts)"
                    ]
            return render_template("tasks.html", tasks=tasks)
        elif focused:
            tasks = [
                        "Work on CS50 project or coding tasks",
                        "Study a challenging concept or chapter",
                        "Solve programming exercises or problem sets",
                        "Write or revise technical notes",
                        "Research a topic for a project",
                        "Plan out a day/week schedule",
                        "Draft a blog post or article",
                        "Complete a small but meaningful work task",
                        "Debug or refactor code",
                        "Learn a new shortcut or tool to improve productivity"
                    ]
            return render_template("tasks.html", tasks=tasks)
        
        elif creative:
            tasks = [
                        "Sketch or paint something new",
                        "Brainstorm ideas for a project or hobby",
                        "Write a short story, poem, or journal creatively",
                        "Try a new recipe or experiment in baking",
                        "Take photos of interesting patterns or scenes",
                        "Rearrange your room for a fresh perspective",
                        "Make DIY crafts or design something",
                        "Compose music, make beats, or try songwriting",
                        "Experiment with colors, textures, or materials",
                        "Build or prototype a small idea (digital or physical)"
                    ]
            return render_template("tasks.html", tasks=tasks)
        
        elif calm:
            tasks = [
                        "Meditate or practice deep breathing for 10 to 15 mins",
                        "Journal thoughts or feelings",
                        "Paint or sketch (watercolor/graphite)",
                        "Listen to calming music or ambient sounds",
                        "Take a walk in nature",
                        "Read a light book or article",
                        "Stretch or do gentle yoga",
                        "Drink tea or make a small self-care ritual",
                        "Organize small things (desk, bookshelf) slowly",
                        "Reflect on goals quietly or visualize your day"
                    ] 
            return render_template("tasks.html", tasks=tasks)
        
        elif tired: 
            tasks = [
                        "Rest or take a short nap (20 to 30 mins)",
                        "Go for a light walk to refresh",
                        "Reply to simple messages or emails",
                        "Drink water or have a small snack",
                        "Listen to music or a podcast passively",
                        "Do light chores (fold laundry, wash dishes)",
                        "Stretch gently or do breathing exercises",
                        "Read a short article or book chapter",
                        "Plan the tasks for the next day while relaxing",
                        "Watch something lighthearted or funny"
                    ]
            return render_template("tasks.html", tasks=tasks)
        
        elif stressed:
            tasks =  [
                        "Declutter a small space (desk, drawer, bag)",
                        "Make a priority list (urgent vs. important)",
                        "Deep breathing or 10-min meditation",
                        "Write down worries to release them on paper",
                        "Go for a walk or light exercise",
                        "Listen to calming or instrumental music",
                        "Set timers for tasks (Pomodoro method)",
                        "Organize digital files or emails",
                        "Take 5 minutes to stretch shoulders/back",
                        "Drink water or a warm tea mindfully"
                    ]
            return render_template("tasks.html", tasks=tasks)

@app.route("/report")
@login_required
def report():

    points = get_points()
    if not points > 1000:
        return "Not enough points yet"

    conn = get_db()
    cursor = conn.cursor()

    cursor.execute("SELECT COUNT(*) FROM tasks WHERE user_id = ?", (session["user_id"], ))
    total_tasks = cursor.fetchone()[0]

    if total_tasks < 1:
        return "Add tasks to see your report"
    
    cursor.execute("SELECT COUNT(*) FROM tasks WHERE user_id = ? AND status = ?", (session["user_id"], "done", ))
    tasks_done = cursor.fetchone()[0]

    productivity = int((tasks_done / total_tasks) * 100)

    return render_template("report.html", total_tasks=total_tasks, tasks_done=tasks_done, productivity=productivity)

if __name__ == '__main__':
    app.run(debug=True, host='127.0.0.1', port=5000)